version: "3.9"
   
services:
  chain_web:
    build: .
    ports:
      - "8000:80"
    networks:
      - chainscan-web

networks:
  chainscan-web:
   driver: bridge
   ipam:
     driver: default
     config:
       - subnet: 172.16.100.0/24
