version: 2.1

executors:
  docker-executor:
    docker:
      - image: ankrnetwork/alpine:v2.0.0
  machine-executor:
    machine: true

commands:
  kubeconfig:
    steps:
      - run:
          name: copy kubeconfig to base image
          command: data=$(cat /root/.kube/oentext ); crypt aes -k=$kubekey -e=false -d=$data > /root/.kube/config

jobs:
  build-with-machine:
    executor: machine-executor
    steps:
      - checkout
      - run: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
      - run: make docker-push

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-with-machine:
          context: cicd
          filters:
            branches:
              ignore:
                - /feature\/.*/
