###
// get block list
GET https://apis-stage.ankr.com/chain-scan/v1/blocks?offset=0&limit=10


###
// get txs list
GET https://apis-stage.ankr.com/chain-scan/v1/txs?offset=0&limit=20


###
// get block
GET https://apis-stage.ankr.com/chain-scan/v1/blocks/55

###
// get block txs
GET https://apis-stage.ankr.com/chain-scan/v1/txs?blockBegin=55&blockEnd=55

###
// get tx
GET https://apis-stage.ankr.com/chain-scan/v1/txs/0x0d6c426707c35c27e4bd7a3f7736e533efa6e73d6b9baa3533cdc8f37d45caaa

###
// get contract address
GET https://apis-stage.ankr.com/chain-scan/v1/accounts/0x84868afcC4Ba758a4ae2aca141D2fF0ECD8C5fac

###
// get account address
GET https://apis-stage.ankr.com/chain-scan/v1/accounts/0xbedb5e825989b8ef4b195bfc3a9196eec35beae4

###
// get address
GET https://apis-stage.ankr.com/chain-scan/v1/accounts?offset=0&limit=100

###
// get address
GET https://apis-stage.ankr.com/chain-scan/v1/accounts/0x2594d5efA1cBb3a5486988f8A5b094E9707539e5/txns

###
// get erc20
GET https://apis-stage.ankr.com/chain-scan/v1/tokens/txns/erc721?offset=0&limit=100

###
// get token type
GET https://apis-stage.ankr.com/chain-scan/v1/tokens/0x84868afcC4Ba758a4ae2aca141D2fF0ECD8C5fac/type

###
// get token holders
GET https://apis-stage.ankr.com/chain-scan/v1/tokens/0x84868afcC4Ba758a4ae2aca141D2fF0ECD8C5fac/holders?type=erc20

###
// get token transfers
GET https://apis-stage.ankr.com/chain-scan/v1/tokens/0x84868afcc4ba758a4ae2aca141d2ff0ecd8c5fac/transfers?type=erc20


###
// get nft transfers
GET https://apis-stage.ankr.com/chain-scan/v1/tokens/0xbedb5e825989b8ef4b195bfc3a9196eec35beae4/transfers?type=erc721

###
// get logs
GET https://apis-stage.ankr.com/chain-scan/v1/txs/0x6de151b9f4f0c2515f3fe3570f6e0b7456934c70677088e19a305c0d4803862c/event-logs